### ISSUE TITLE
Could you let me know does this lib support Visual Studio?

### ISSUE THREAD

**Issue by eliteYang** [bolero-MURAKAMI/Sprout#81]
Could you let me know does this lib support Visual Studio? Thanks a lot.

**Comment by bolero-MURAKAMI** [comment]
Thanks for asking.

An answer is "partially yes".
You will some of the features of Sprout in VC++ can be used "at run time."
Many features are not available at compile time.
It is due to a bug in the VC++.

For example, VS2015 can not initialize the constexpr specified variable of non-integer by constant expression.
http://melpon.org/wandbox/permlink/mcJe62iNzmapWHks

But I would like to correspond as much as possible.
If you could not use function you want is in VC++, please report to me.

**Comment by eliteYang** [comment]
@bolero-MURAKAMI Thanks a lot, I‘ll try it in windows
